### ISSUE TITLE
Out of bounds error in SciPy solver

### ISSUE THREAD

**Issue by johnzl-777** [aws/amazon-braket-default-simulator-python#176]
**Describe the bug**
Trying to run the following task:
```python
from braket.devices import LocalSimulator
from braket.ir.ahs import Program

task_json = {
  "braketSchemaHeader": {
    "name": "braket.ir.ahs.program",
    "version": "1"
  },
  "setup": {
    "ahs_register": {
      "sites": [
        [
          "0E-8",
          "0E-8"
        ],
        [
          "0.00000610",
          "0E-8"
        ],
        [
          "0.00001220",
          "0E-8"
        ],
        [
          "0.00001830",
          "0E-8"
        ],
        [
          "0.00002440",
          "0E-8"
        ],
        [
          "0.00003050",
          "0E-8"
        ],
        [
          "0.00003660",
          "0E-8"
        ],
        [
          "0.00004270",
          "0E-8"
        ],
        [
          "0.00004880",
          "0E-8"
        ],
        [
          "0.00005490",
          "0E-8"
        ],
        [
          "0.00006100",
          "0E-8"
        ]
      ],
      "filling": [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    }
  },
  "hamiltonian": {
    "drivingFields": [
      {
        "amplitude": {
          "time_series": {
            "values": [
              "0.0",
              "15700000.0",
              "15700000.0",
              "0.0"
            ],
            "times": [
              "0E-9",
              "3.00E-7",
              "6.00E-7",
              "6.60E-7"
            ]
          },
          "pattern": "uniform"
        },
        "phase": {
          "time_series": {
            "values": [
              "0E-7",
              "0E-7"
            ],
            "times": [
              "0E-9",
              "6.60E-7"
            ]
          },
          "pattern": "uniform"
        },
        "detuning": {
          "time_series": {
            "values": [
              "-18800000.0",
              "-18800000.0",
              "-12218750.0",
              "0.0"
            ],
            "times": [
              "0E-9",
              "3.00E-7",
              "6.00E-7",
              "6.60E-7"
            ]
          },
          "pattern": "uniform"
        }
      }
    ],
    "shiftingFields": []
  }
}

LocalSimulator("braket_ahs").run(Program(**task_json), shots = 10)
```
produces the following error:
```
capi_return is NULL
Call-back cb_f_in_zvode__user__routines failed.
Fatal Python error: F2PySwapThreadLocalCallbackPtr: F2PySwapThreadLocalCallbackPtr: PyLong_AsVoidPtr failed
Python runtime state: initialized
Traceback (most recent call last):
  File "/Users/jlong/Desktop/Github/bloqade-python/.venv/lib/python3.11/site-packages/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py", line 82, in f
    return -1j * dt * _apply_hamiltonian(index_time, operators_coefficients, y)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlong/Desktop/Github/bloqade-python/.venv/lib/python3.11/site-packages/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py", line 566, in _apply_hamiltonian
    output_register += (rabi_coef[index_time] / 2) * rabi_op.dot(input_register)
                        ~~~~~~~~~^^^^^^^^^^^^
IndexError: index 1000 is out of bounds for axis 0 with size 1000

Extension modules: pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_lapack, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct (total: 98)
[1]    82110 abort      python whitepaper/bug-report.py
```

**To reproduce**
See above

**Expected behavior**
Successful execution of emulator

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.43.0
- **Amazon Braket Python Schemas version**: 1.17.0
- **Amazon Braket Python Default Simulator version**:1.14.0.post0
- **Python version**: 3.11.3

**Comment by johnzl-777** [comment]
Just got the chance to test this, this fixes the issue!
